import { EmberTypedValue } from '../types/types';
export { Invocation, InvocationImpl };
/**
 *  Part of a consumer's command that requests the invocation of the parent function
 *  by a provider.
 */
interface Invocation {
    /** Identifier generated by the consumer and used to link invocations to their
     *  invocation results. */
    id?: number;
    /** Values of the arguments associated with the funtion. */
    args: Array<EmberTypedValue>;
}
declare class InvocationImpl implements Invocation {
    id: number | undefined;
    args: Array<EmberTypedValue>;
    constructor(id: number | undefined, args: Array<EmberTypedValue>);
}
