dist: bionic
language: node_js
matrix:
  include:
    - os: linux
      language: node_js
      node_js: "12"
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - npm run dist 
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine


