import { EmberTypedValue } from '../types/types'

export { Invocation, InvocationImpl }

/**
 *  Part of a consumer's command that requests the invocation of the parent function
 *  by a provider.
 */
interface Invocation {
	/** Identifier generated by the consumer and used to link invocations to their
	 *  invocation results. */
	id?: number
	/** Values of the arguments associated with the funtion. */
	args: Array<EmberTypedValue>
}

class InvocationImpl implements Invocation {
	constructor(public id: number | undefined, public args: Array<EmberTypedValue>) {}
}
